### ISSUE TITLE
Any plans to update to access BabelNet v5?

### ISSUE THREAD

**Issue by colingoldberg** [tomayac/babelnet_js#1]
Hi,

Inspection of babelnet.js shows it accesses v1 (START_POINT: 'https://babelnet.io/v1/').

Any plans to update to access the latest version (v5)?

Colin Goldberg

**Comment by tomayac** [comment]
Hi Colin,

I am on vacation at the moment, but given enough interest I could probably justify the effort to update the library upon my return. Compared to just using the API directly, how much of a value-add do you consider the library to be?

Thanks,
Tom

**Comment by colingoldberg** [comment]
Hi Tom,

I hope you are enjoying your vacation. The truth is that I had already coded a test using the API directly, but, noticing the v1/v5 issue, and that you still had some download activity, I thought I would raise the issue. I will probably not use the package (there is also a difference in functions available - getSynsetIdsFromWikipediaTitle is not listed now on http://babelnet.org/guide).

Actually, what I was looking to find is a full description, together with examples, of the responses to requests such as "getSynset" - to help me understand the underlying model. 

I have just noticed, though, that I have a lot to learn about the history of the BabelNet resource, the various steps taken over the years (eg. the Lemon Model, Linguistic Linked Data, etc.), and the current state of the art. What I am looking to do is to be able to access what I would consider as an taxonomy/ontology for a given domain, and/or an "upper ontology", with sufficient information about synonyms, senses, etc., and also containing support for semantic parsing/processing. A big challenge...

Thanks
Colin

**Comment by tomayac** [comment]
> I will probably not use the package

@colingoldberg Fair enough, I have abandoned the project after `v1`, when I needed to use it. Maybe [Roberto Navigli](mailto:navigli@di.uniroma1.it) and team are interested in maintaining it? You could probably ping them. I would happily transfer ownership to anyone interested. Feel free to re-open if you succeed in finding a new owner, I'm closing the issue for now.
